// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"time"
)

type Feed struct {
	ID        interface{}
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Url       string
}

type User struct {
	ID        interface{}
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
}
